Repository KccTrio/final_project, pull requests merged in 2024-10, with the labels that each got.

#3 feat: component navbar 개발 feat
  src/main/java/com/kcc/trioffice/controller/TestController.java
  src/main/webapp/WEB-INF/views/component/first-side-bar.jsp
  src/main/webapp/WEB-INF/views/component/lib.jsp
  src/main/webapp/WEB-INF/views/component/main-contents.jsp
  src/main/webapp/WEB-INF/views/component/nav.jsp
  src/main/webapp/WEB-INF/views/component/second-side-bar.jsp
  src/main/webapp/WEB-INF/views/component/top-bar.jsp
  src/main/webapp/static/component/first-side-bar.css
  src/main/webapp/static/component/main-contents.css
  src/main/webapp/static/component/nav.css
  src/main/webapp/static/component/reset.css
  src/main/webapp/static/component/second-side-bar.css
  src/main/webapp/static/component/top-bar.css
  src/main/webapp/static/component/top-bar.js
Labels: feat

#5 feat: 채팅 생성 페이지, 채팅 조회 페이지
  pom.xml
  src/main/java/com/kcc/trioffice/domain/chat_room/controller/ChatRoomController.java
  src/main/java/com/kcc/trioffice/domain/chat_room/controller/ChatRoomSocketController.java
  src/main/java/com/kcc/trioffice/domain/chat_room/dto/request/ChatMessage.java
  src/main/java/com/kcc/trioffice/domain/chat_room/dto/request/ChatRoomCreate.java
  src/main/java/com/kcc/trioffice/domain/chat_room/mapper/ChatRoomMapper.java
  src/main/java/com/kcc/trioffice/domain/chat_room/mapper/ParticipationEmployeeMapper.java
  src/main/java/com/kcc/trioffice/domain/chat_room/service/ChatRoomService.java
  src/main/java/com/kcc/trioffice/domain/employee/controller/EmployeeRestController.java
  src/main/java/com/kcc/trioffice/domain/employee/dto/response/EmployeeInfo.java
  src/main/java/com/kcc/trioffice/domain/employee/dto/response/SearchEmployee.java
  src/main/java/com/kcc/trioffice/domain/employee/mapper/EmployeeMapper.java
  src/main/java/com/kcc/trioffice/domain/employee/service/EmployeeService.java
  src/main/java/com/kcc/trioffice/global/config/WebSocketConfig.java
  src/main/java/com/kcc/trioffice/global/exception/GlobalExceptionHandler.java
  src/main/java/com/kcc/trioffice/global/exception/type/BadRequestException.java
  src/main/java/com/kcc/trioffice/global/exception/type/BaseException.java
  src/main/java/com/kcc/trioffice/global/exception/type/NotFoundException.java
  src/main/resources/mapper/chat-room.xml
  src/main/resources/mapper/employee.xml
  src/main/resources/mapper/participation-employee.xml
  src/main/webapp/WEB-INF/views/chat_room/chat-room-list.jsp
  src/main/webapp/WEB-INF/views/chat_room/chat-room-save.jsp
  src/main/webapp/WEB-INF/views/component/lib.jsp
  src/main/webapp/static/chat_room/chat-room-list.css
  src/main/webapp/static/chat_room/chat-room-list.js
  src/main/webapp/static/chat_room/chat-room-save.css
  src/main/webapp/static/chat_room/chat-room-save.js
  src/main/webapp/static/chat_room/chat-room.css
  src/main/webapp/static/component/first-side-bar.css
  src/main/webapp/static/component/main-contents.css
  src/main/webapp/static/component/reset.css
  src/main/webapp/static/component/second-side-bar.css
Labels: feat

#13 feat: 채팅 이모티콘 및 읽음 처리
  src/main/java/com/kcc/trioffice/domain/chat_room/controller/ChatRoomRestController.java
  src/main/java/com/kcc/trioffice/domain/chat_room/controller/ChatRoomSocketController.java
  src/main/java/com/kcc/trioffice/domain/chat_room/dto/request/ChatMessage.java
  src/main/java/com/kcc/trioffice/domain/chat_room/dto/response/ChatDetailInfo.java
  src/main/java/com/kcc/trioffice/domain/chat_room/dto/response/ChatInfo.java
  src/main/java/com/kcc/trioffice/domain/chat_room/dto/response/ChatMessageInfo.java
  src/main/java/com/kcc/trioffice/domain/chat_room/dto/response/ChatRoomDetailInfo.java
  src/main/java/com/kcc/trioffice/domain/chat_room/dto/response/ParticipantEmployeeInfo.java
  src/main/java/com/kcc/trioffice/domain/chat_room/mapper/ChatMapper.java
  src/main/java/com/kcc/trioffice/domain/chat_room/mapper/ChatRoomMapper.java
  src/main/java/com/kcc/trioffice/domain/chat_room/mapper/ParticipationEmployeeMapper.java
  src/main/java/com/kcc/trioffice/domain/chat_room/service/ChatRoomService.java
  src/main/java/com/kcc/trioffice/domain/chat_status/controller/ChatStatusRestController.java
  src/main/java/com/kcc/trioffice/domain/chat_status/dto/request/UpdateEmoticon.java
  src/main/java/com/kcc/trioffice/domain/chat_status/dto/response/ChatStatusInfo.java
  src/main/java/com/kcc/trioffice/domain/chat_status/dto/response/EmoticonMessage.java
  src/main/java/com/kcc/trioffice/domain/chat_status/dto/response/EmoticonStatus.java
  src/main/java/com/kcc/trioffice/domain/chat_status/mapper/ChatStatusMapper.java
  src/main/java/com/kcc/trioffice/domain/chat_status/service/ChatStatusService.java
  src/main/java/com/kcc/trioffice/domain/employee/controller/EmployeeRestController.java
  src/main/java/com/kcc/trioffice/domain/employee/service/EmployeeService.java
  src/main/java/com/kcc/trioffice/global/config/WebSocketConfig.java
  src/main/java/com/kcc/trioffice/global/enums/EmoticonType.java
  src/main/java/com/kcc/trioffice/global/handler/StompHandler.java
  src/main/resources/mapper/chat-room.xml
  src/main/resources/mapper/chat-status.xml
  src/main/resources/mapper/chat.xml
  src/main/resources/mapper/participation-employee.xml
  src/main/webapp/WEB-INF/views/chat_room/chat-room-list.jsp
  src/main/webapp/static/chat_room/chat-room-list.css
  src/main/webapp/static/chat_room/chat-room-list.js
  src/main/webapp/static/chat_room/chat-room.js
  src/main/webapp/static/component/second-side-bar.css
  src/main/webapp/static/component/top-bar.css
Labels: feat

#7 feat: 로그인, 비밀번호 찾기 개발 feat
  pom.xml
  src/main/java/com/kcc/trioffice/controller/TestController.java
  src/main/java/com/kcc/trioffice/domain/employee/controller/EmployeeContoller.java
  src/main/java/com/kcc/trioffice/domain/employee/controller/EmployeeRestController.java
  src/main/java/com/kcc/trioffice/domain/employee/dto/request/SaveEmployee.java
  src/main/java/com/kcc/trioffice/domain/employee/dto/response/AdminInfo.java
  src/main/java/com/kcc/trioffice/domain/employee/dto/response/EmployeeInfo.java
  src/main/java/com/kcc/trioffice/domain/employee/mapper/EmployeeMapper.java
  src/main/java/com/kcc/trioffice/domain/employee/service/EmployeeService.java
  src/main/java/com/kcc/trioffice/global/auth/PrincipalDetail.java
  src/main/java/com/kcc/trioffice/global/auth/PrincipalDetailService.java
  src/main/java/com/kcc/trioffice/global/config/MailConfig.java
  src/main/java/com/kcc/trioffice/global/config/SecurityConfig.java
  src/main/java/com/kcc/trioffice/global/exception/type/BaseException.java
  src/main/java/com/kcc/trioffice/global/exception/type/EmployeeSaveException.java
  src/main/java/com/kcc/trioffice/global/exception/type/NotFoundException.java
  src/main/java/com/kcc/trioffice/global/init/InitEmployee.java
  src/main/java/com/kcc/trioffice/global/util/PasswordEncoderUtil.java
  src/main/resources/mapper/employee.xml
  src/main/webapp/WEB-INF/views/component/alram.jsp
  src/main/webapp/WEB-INF/views/component/first-side-bar.jsp
  src/main/webapp/WEB-INF/views/component/lib.jsp
  src/main/webapp/WEB-INF/views/component/top-bar.jsp
  src/main/webapp/WEB-INF/views/user/find-password-done.jsp
  src/main/webapp/WEB-INF/views/user/find-password-email.jsp
  src/main/webapp/WEB-INF/views/user/find-password.jsp
  src/main/webapp/WEB-INF/views/user/login.jsp
  src/main/webapp/static/component/first-side-bar.css
  src/main/webapp/static/component/first-side-bar.js
  src/main/webapp/static/component/kcc-logo-no-title.png
  src/main/webapp/static/component/kcc-logo.png
  src/main/webapp/static/component/second-side-bar.css
  src/main/webapp/static/component/top-bar.css
  src/main/webapp/static/component/top-bar.js
  src/main/webapp/static/user/find-password-empty-check.js
  src/main/webapp/static/user/find-password.css
  src/main/webapp/static/user/find-password.js
  src/main/webapp/static/user/login.css
  src/main/webapp/static/user/login.js
Labels: feat

#19 feat: 채팅방 최적화
  src/main/java/com/kcc/trioffice/domain/chat_room/controller/ChatRoomController.java
  src/main/java/com/kcc/trioffice/domain/chat_room/controller/ChatRoomRestController.java
  src/main/java/com/kcc/trioffice/domain/chat_room/controller/ChatRoomSocketController.java
  src/main/java/com/kcc/trioffice/domain/chat_room/dto/response/ChatMessageAndParticipants.java
  src/main/java/com/kcc/trioffice/domain/chat_room/mapper/ChatRoomMapper.java
  src/main/java/com/kcc/trioffice/domain/chat_room/service/ChatRoomService.java
  src/main/java/com/kcc/trioffice/domain/chat_status/controller/ChatStatusRestController.java
  src/main/java/com/kcc/trioffice/domain/chat_status/dto/response/EmoticonMessage.java
  src/main/java/com/kcc/trioffice/domain/employee/controller/EmployeeRestController.java
  src/main/java/com/kcc/trioffice/domain/participation_employee/controller/ParticipationEmployeeRestController.java
  src/main/java/com/kcc/trioffice/domain/participation_employee/mapper/ParticipationEmployeeMapper.java
  src/main/java/com/kcc/trioffice/global/auth/PrincipalDetail.java
  src/main/resources/mapper/chat-room.xml
  src/main/resources/mapper/chat-status.xml
  src/main/resources/mapper/chat.xml
  src/main/resources/mapper/employee.xml
  src/main/resources/mapper/participation-employee.xml
  src/main/webapp/WEB-INF/views/chat_room/chat-room-list.jsp
  src/main/webapp/static/chat_room/chat-room-list.css
  src/main/webapp/static/chat_room/chat-room.js
Labels: feat

#21 feat: 채팅방 나가기
  src/main/java/com/kcc/trioffice/domain/chat_room/controller/ChatRoomController.java
  src/main/java/com/kcc/trioffice/domain/chat_room/controller/ChatRoomRestController.java
  src/main/java/com/kcc/trioffice/domain/chat_room/dto/response/ChatMessageInfo.java
  src/main/java/com/kcc/trioffice/domain/chat_room/dto/response/DeleteChatRoom.java
  src/main/java/com/kcc/trioffice/domain/chat_room/mapper/ChatRoomMapper.java
  src/main/java/com/kcc/trioffice/domain/chat_room/service/ChatRoomService.java
  src/main/java/com/kcc/trioffice/domain/participation_employee/mapper/ParticipationEmployeeMapper.java
  src/main/java/com/kcc/trioffice/global/enums/ChatType.java
  src/main/resources/mapper/chat-room.xml
  src/main/resources/mapper/employee.xml
  src/main/resources/mapper/participation-employee.xml
  src/main/webapp/WEB-INF/views/chat_room/chat-room-list.jsp
  src/main/webapp/WEB-INF/views/chat_room/modal/chat-room-dropdown.jsp
  src/main/webapp/static/chat_room/chat-room.js
  src/main/webapp/static/chat_room/modal/chat-room-dropdown.css
  src/main/webapp/static/chat_room/modal/chat-room-dropdown.js
Labels: feat

#23 feat: 채팅방 입/퇴장 시 이벤트
  src/main/java/com/kcc/trioffice/domain/chat_room/controller/ChatRoomRestController.java
  src/main/java/com/kcc/trioffice/domain/chat_room/dto/response/ChatMessageInfoAndPtptEmp.java
  src/main/java/com/kcc/trioffice/domain/chat_room/dto/response/ChatRoomEnter.java
  src/main/java/com/kcc/trioffice/domain/chat_room/mapper/ChatRoomMapper.java
  src/main/java/com/kcc/trioffice/domain/chat_room/service/ChatRoomService.java
  src/main/java/com/kcc/trioffice/domain/chat_status/mapper/ChatStatusMapper.java
  src/main/java/com/kcc/trioffice/domain/chat_status/service/ChatStatusService.java
  src/main/java/com/kcc/trioffice/domain/participation_employee/controller/ParticipationEmployeeRestController.java
  src/main/java/com/kcc/trioffice/domain/participation_employee/mapper/ParticipationEmployeeMapper.java
  src/main/java/com/kcc/trioffice/domain/participation_employee/service/ParticipationEmployeeService.java
  src/main/java/com/kcc/trioffice/global/event/ptptEvent.java
  src/main/java/com/kcc/trioffice/global/handler/StompHandler.java
  src/main/resources/mapper/chat-room.xml
  src/main/resources/mapper/chat-status.xml
  src/main/resources/mapper/participation-employee.xml
  src/main/webapp/WEB-INF/views/chat_room/chat-room-list.jsp
  src/main/webapp/static/chat_room/chat-room.css
  src/main/webapp/static/chat_room/chat-room.js
Labels: feat, fix

#27 refector: 로그인 실패시 알림
  src/main/webapp/WEB-INF/views/user/login.jsp
  src/main/webapp/static/user/login.css
Labels: refactor

#30 feat: 파일 조회
  src/main/java/com/kcc/trioffice/domain/attached_file/controller/AttachedFileRestController.java
  src/main/java/com/kcc/trioffice/domain/attached_file/dto/response/AttachedFileInfo.java
  src/main/java/com/kcc/trioffice/domain/attached_file/mapper/AttachedFileMapper.java
  src/main/java/com/kcc/trioffice/domain/attached_file/service/AttachedFileService.java
  src/main/resources/mapper/attached-file.xml
  src/main/webapp/WEB-INF/views/chat_room/chat-room-list.jsp
  src/main/webapp/WEB-INF/views/chat_room/modal/add-emp-modal.jsp
  src/main/webapp/static/chat_room/chat-room-list.css
  src/main/webapp/static/chat_room/chat-room-save.css
  src/main/webapp/static/chat_room/chat-room.js
Labels: feat, refactor

#32 feat: 조직도 조회
  src/main/java/com/kcc/trioffice/controller/TestController.java
  src/main/java/com/kcc/trioffice/domain/department/controller/DepartmentController.java
  src/main/java/com/kcc/trioffice/domain/department/dto/response/Department.java
  src/main/java/com/kcc/trioffice/domain/department/mapper/DepartmentMapper.java
  src/main/java/com/kcc/trioffice/domain/department/service/DepartmentService.java
  src/main/java/com/kcc/trioffice/domain/employee/controller/EmployeeRestController.java
  src/main/java/com/kcc/trioffice/domain/employee/service/EmployeeService.java
  src/main/resources/mapper/department.xml
  src/main/webapp/WEB-INF/views/department/adminDepartment.jsp
  src/main/webapp/WEB-INF/views/department/employees.jsp
  src/main/webapp/static/department/adminDepartment.css
Labels: feat

#33 style: xml 들여쓰기 통일
  src/main/resources/mapper/attached-file.xml
  src/main/resources/mapper/chat-room.xml
  src/main/resources/mapper/chat-status.xml
  src/main/resources/mapper/chat.xml
  src/main/resources/mapper/employee.xml
  src/main/resources/mapper/participation-employee.xml
  src/main/resources/mapper/schedule.xml
  src/main/resources/mapper/tag.xml
Labels: refactor

#34 feat: 푸시 알림
  .gitignore
  pom.xml
  src/main/java/com/kcc/trioffice/controller/TestController.java
  src/main/java/com/kcc/trioffice/domain/attached_file/service/AttachedFileService.java
  src/main/java/com/kcc/trioffice/domain/chat_room/service/ChatRoomService.java
  src/main/java/com/kcc/trioffice/domain/employee/controller/EmployeeRestController.java
  src/main/java/com/kcc/trioffice/domain/employee/dto/request/SaveFcmToken.java
  src/main/java/com/kcc/trioffice/domain/employee/dto/response/EmployeeInfo.java
  src/main/java/com/kcc/trioffice/domain/employee/mapper/EmployeeMapper.java
  src/main/java/com/kcc/trioffice/domain/employee/service/EmployeeService.java
  src/main/java/com/kcc/trioffice/domain/notification/controller/NotificationController.java
  src/main/java/com/kcc/trioffice/domain/notification/controller/NotificationRestController.java
  src/main/java/com/kcc/trioffice/domain/notification/dto/request/SendPushDto.java
  src/main/java/com/kcc/trioffice/domain/notification/service/FcmService.java
  src/main/java/com/kcc/trioffice/domain/participation_employee/mapper/ParticipationEmployeeMapper.java
  src/main/java/com/kcc/trioffice/domain/participation_employee/service/ParticipationEmployeeService.java
  src/main/java/com/kcc/trioffice/global/config/AsyncConfig.java
  src/main/resources/mapper/attached-file.xml
  src/main/resources/mapper/chat.xml
  src/main/resources/mapper/participation-employee.xml
  src/main/webapp/WEB-INF/views/chat_room/chat-room-list.jsp
  src/main/webapp/WEB-INF/views/component/firebase-config.jsp
  src/main/webapp/WEB-INF/views/component/lib.jsp
  src/main/webapp/WEB-INF/views/test-noti.jsp
Labels: feat

#36 feat: 채팅 삭제
  src/main/java/com/kcc/trioffice/domain/chat_room/controller/ChatRoomRestController.java
  src/main/java/com/kcc/trioffice/domain/chat_room/dto/response/ChatDelete.java
  src/main/java/com/kcc/trioffice/domain/chat_room/dto/response/ChatInfo.java
  src/main/java/com/kcc/trioffice/domain/chat_room/mapper/ChatMapper.java
  src/main/java/com/kcc/trioffice/domain/chat_room/service/ChatRoomService.java
  src/main/java/com/kcc/trioffice/global/event/PtptEvent.java
  src/main/resources/mapper/attached-file.xml
  src/main/resources/mapper/chat-room.xml
  src/main/resources/mapper/chat-status.xml
  src/main/resources/mapper/chat.xml
  src/main/resources/mapper/employee.xml
  src/main/resources/mapper/participation-employee.xml
  src/main/resources/mapper/schedule.xml
  src/main/webapp/WEB-INF/views/chat_room/chat-room-list.jsp
  src/main/webapp/WEB-INF/views/chat_room/modal/chat-delete-dropdown.jsp
  src/main/webapp/static/chat_room/chat-room.js
  src/main/webapp/static/chat_room/modal/chat-room-dropdown.css
  src/main/webapp/static/chat_room/modal/chat-room-dropdown.js
Labels: feat

#39 feat: 채팅방 즐겨찾기
  src/main/java/com/kcc/trioffice/domain/chat_room/controller/ChatRoomRestController.java
  src/main/java/com/kcc/trioffice/domain/chat_room/dto/response/ChatRoomInfo.java
  src/main/java/com/kcc/trioffice/domain/chat_room/mapper/ChatRoomMapper.java
  src/main/java/com/kcc/trioffice/domain/chat_room/service/ChatRoomService.java
  src/main/java/com/kcc/trioffice/domain/participation_employee/mapper/ParticipationEmployeeMapper.java
  src/main/resources/mapper/chat-room.xml
  src/main/resources/mapper/participation-employee.xml
  src/main/webapp/WEB-INF/views/chat_room/chat-room-list.jsp
  src/main/webapp/WEB-INF/views/chat_room/modal/chat-room-dropdown.jsp
  src/main/webapp/static/chat_room/chat-room.css
  src/main/webapp/static/chat_room/chat-room.js
  src/main/webapp/static/chat_room/modal/chat-room-dropdown.js
Labels: feat

#42 feat: 일정등록 일정상세보기
  src/main/java/com/kcc/trioffice/domain/employee/controller/EmployeeRestController.java
  src/main/java/com/kcc/trioffice/domain/employee/mapper/EmployeeMapper.java
  src/main/java/com/kcc/trioffice/domain/employee/service/EmployeeService.java
  src/main/java/com/kcc/trioffice/domain/schedule/controller/ScheduleContorller.java
  src/main/java/com/kcc/trioffice/domain/schedule/controller/ScheduleRestController.java
  src/main/java/com/kcc/trioffice/domain/schedule/dto/ComponentDto.java
  src/main/java/com/kcc/trioffice/domain/schedule/dto/EmployeeSchedules.java
  src/main/java/com/kcc/trioffice/domain/schedule/dto/SaveSchedule.java
  src/main/java/com/kcc/trioffice/domain/schedule/dto/ScheduleDetail.java
  src/main/java/com/kcc/trioffice/domain/schedule/dto/ScheduleDetailEmployees.java
  src/main/java/com/kcc/trioffice/domain/schedule/mapper/ScheduleMapper.java
  src/main/java/com/kcc/trioffice/domain/schedule/service/ScheduleService.java
  src/main/java/com/kcc/trioffice/global/init/InitEmployee.java
  src/main/resources/mapper/employee.xml
  src/main/resources/mapper/schedule.xml
  src/main/webapp/WEB-INF/views/component/lib.jsp
  src/main/webapp/WEB-INF/views/component/top-bar.jsp
  src/main/webapp/WEB-INF/views/schedule/schedule.jsp
  src/main/webapp/static/component/first-side-bar.css
  src/main/webapp/static/component/fullcalendar/LICENSE.md
  src/main/webapp/static/component/fullcalendar/README.md
  src/main/webapp/static/component/fullcalendar/examples/background-events.html
  src/main/webapp/static/component/fullcalendar/examples/daygrid-views.html
  src/main/webapp/static/component/fullcalendar/examples/external-dragging-2cals.html
  src/main/webapp/static/component/fullcalendar/examples/external-dragging-builtin.html
  src/main/webapp/static/component/fullcalendar/examples/full-height.html
  src/main/webapp/static/component/fullcalendar/examples/list-sticky-header.html
  src/main/webapp/static/component/fullcalendar/examples/list-views.html
  src/main/webapp/static/component/fullcalendar/examples/month-view.html
  src/main/webapp/static/component/fullcalendar/examples/multimonth-view.html
  src/main/webapp/static/component/fullcalendar/examples/multiweek-view.html
  src/main/webapp/static/component/fullcalendar/examples/natural-height.html
  src/main/webapp/static/component/fullcalendar/examples/selectable.html
  src/main/webapp/static/component/fullcalendar/examples/timegrid-views-modal.html
  src/main/webapp/static/component/fullcalendar/examples/timegrid-views.html
  src/main/webapp/static/component/mobiscroll/icons_mobiscroll.ttf
  src/main/webapp/static/component/mobiscroll/icons_mobiscroll.woff
  src/main/webapp/static/component/mobiscroll/mobiscroll.javascript.min.css
  src/main/webapp/static/component/mobiscroll/mobiscroll.javascript.min.js
  src/main/webapp/static/component/reset.css
  src/main/webapp/static/component/top-bar.css
  src/main/webapp/static/schedule/schedule.css
  src/main/webapp/static/schedule/schedule.js
Labels: feat

#44 feat: 일정 삭제
  pom.xml
  src/main/java/com/kcc/trioffice/domain/schedule/controller/ScheduleRestController.java
  src/main/java/com/kcc/trioffice/domain/schedule/mapper/ScheduleMapper.java
  src/main/java/com/kcc/trioffice/domain/schedule/service/ScheduleService.java
  src/main/java/com/kcc/trioffice/global/exception/type/ScheduleDeleteException.java
  src/main/resources/mapper/schedule.xml
  src/main/webapp/WEB-INF/views/schedule/schedule.jsp
  src/main/webapp/static/schedule/schedule.css
  src/main/webapp/static/schedule/schedule.js
Labels: feat

#47 feat: 알림 페이지
  src/main/java/com/kcc/trioffice/domain/notification/controller/NotificationController.java
  src/main/resources/mapper/attached-file.xml
  src/main/resources/mapper/chat-room.xml
  src/main/resources/mapper/chat.xml
  src/main/resources/mapper/schedule.xml
  src/main/webapp/WEB-INF/views/chat_room/chat-room-list.jsp
  src/main/webapp/WEB-INF/views/chat_room/modal/add-emp-modal.jsp
  src/main/webapp/WEB-INF/views/chat_room/modal/image-detail-modal.jsp
  src/main/webapp/WEB-INF/views/chat_room/modal/participant-emp-modal.jsp
  src/main/webapp/WEB-INF/views/chat_room/modal/send-file-modal.jsp
  src/main/webapp/WEB-INF/views/notification/notification.jsp
  src/main/webapp/WEB-INF/views/schedule/schedule.jsp
  src/main/webapp/static/chat_room/chat-room-list.css
  src/main/webapp/static/component/first-side-bar.css
  src/main/webapp/static/component/main-contents.css
  src/main/webapp/static/component/second-side-bar.css
  src/main/webapp/static/component/top-bar.css
  src/main/webapp/static/notification/notification.css
Labels: feat, refactor

#49 setting: CI/CD
  .github/workflows/work.yml
  .gitignore
  Dockerfile
Labels: setting

#52 hoxfix: 일정 jsp
  src/main/webapp/WEB-INF/views/schedule/schedule.jsp
  src/main/webapp/static/schedule/schedule.css
Labels: fix

#53 fix : font
  src/main/webapp/WEB-INF/views/component/first-side-bar.jsp
  src/main/webapp/WEB-INF/views/component/lib.jsp
  src/main/webapp/static/component/first-side-bar.css
  src/main/webapp/static/component/first-side-bar.js
  src/main/webapp/static/component/top-bar.css
  src/main/webapp/static/schedule/schedule.js
Labels: fix

#55 setting: redis session 설정
  pom.xml
  src/main/java/com/kcc/trioffice/global/config/SessionConfig.java
  src/main/webapp/static/chat_room/chat-room-list.css
  src/main/webapp/static/chat_room/chat-room.css
  src/main/webapp/static/chat_room/chat-room.js
  src/main/webapp/static/component/second-side-bar.css
Labels: setting

#57 feat: 조직도로 채팅 추가
  src/main/java/com/kcc/trioffice/domain/department/controller/DepartmentRestController.java
  src/main/java/com/kcc/trioffice/domain/department/dto/response/DepartmentInfo.java
  src/main/java/com/kcc/trioffice/domain/department/dto/response/TreeNode.java
  src/main/java/com/kcc/trioffice/domain/department/mapper/DepartmentMapper.java
  src/main/java/com/kcc/trioffice/domain/department/service/DepartmentService.java
  src/main/java/com/kcc/trioffice/domain/employee/dto/response/SearchEmployee.java
  src/main/resources/mapper/department.xml
  src/main/resources/mapper/employee.xml
  src/main/webapp/WEB-INF/views/chat_room/chat-room-list.jsp
  src/main/webapp/WEB-INF/views/chat_room/modal/add-department-chat-modal.jsp
  src/main/webapp/static/chat_room/chat-room-save.css
  src/main/webapp/static/chat_room/chat-room-save.js
  src/main/webapp/static/chat_room/modal/add-department-chat-modal.css
Labels: feat

#58 refactor: 조직도로 추가 css 변경 및 js 선택자 변경
  src/main/webapp/WEB-INF/views/chat_room/chat-room-list.jsp
  src/main/webapp/static/chat_room/chat-room-save.css
  src/main/webapp/static/chat_room/chat-room-save.js
Labels: refactor

#60 feat: 알림 조회, 일정 참가/거절
  .github/workflows/work.yml
  src/main/java/com/kcc/trioffice/domain/employee/mapper/EmployeeMapper.java
  src/main/java/com/kcc/trioffice/domain/notification/controller/NotificationController.java
  src/main/java/com/kcc/trioffice/domain/notification/controller/NotificationRestController.java
  src/main/java/com/kcc/trioffice/domain/notification/dto/response/NotificationInfo.java
  src/main/java/com/kcc/trioffice/domain/notification/mapper/NotificationMapper.java
  src/main/java/com/kcc/trioffice/domain/notification/service/NotificationService.java
  src/main/java/com/kcc/trioffice/domain/schedule/controller/ScheduleRestController.java
  src/main/java/com/kcc/trioffice/domain/schedule/dto/SaveSchedule.java
  src/main/java/com/kcc/trioffice/domain/schedule/dto/ScheduleDetail.java
  src/main/java/com/kcc/trioffice/domain/schedule/mapper/ScheduleMapper.java
  src/main/java/com/kcc/trioffice/domain/schedule/service/ScheduleService.java
  src/main/java/com/kcc/trioffice/global/enums/NotificationType.java
  src/main/java/com/kcc/trioffice/global/enums/ScheduleInviteType.java
  src/main/resources/mapper/notification.xml
  src/main/resources/mapper/schedule.xml
  src/main/webapp/WEB-INF/views/notification/notification.jsp
  src/main/webapp/static/notification/notification.css
  src/main/webapp/static/notification/notification.js
Labels: feat

#63 feat: 사용자 상태 확인
  src/main/java/com/kcc/trioffice/domain/chat_room/dto/response/ChatRoomDetailInfo.java
  src/main/java/com/kcc/trioffice/domain/chat_room/dto/response/ChatRoomInfo.java
  src/main/java/com/kcc/trioffice/domain/chat_room/service/ChatRoomService.java
  src/main/java/com/kcc/trioffice/domain/employee/controller/EmployeeRestController.java
  src/main/java/com/kcc/trioffice/domain/employee/dto/request/UpdateStatus.java
  src/main/java/com/kcc/trioffice/domain/employee/dto/response/EmployeeInfo.java
  src/main/java/com/kcc/trioffice/domain/employee/mapper/EmployeeMapper.java
  src/main/java/com/kcc/trioffice/domain/employee/service/EmployeeService.java
  src/main/java/com/kcc/trioffice/global/enums/StatusType.java
  src/main/resources/mapper/employee.xml
  src/main/webapp/WEB-INF/views/chat_room/chat-room-list.jsp
  src/main/webapp/WEB-INF/views/component/lib.jsp
  src/main/webapp/static/chat_room/chat-room.css
  src/main/webapp/static/chat_room/chat-room.js
  src/main/webapp/static/component/common.js
Labels: feat

#64 feat: 챗봇
  .prettierignore
  pom.xml
  src/main/java/com/kcc/trioffice/domain/chat_bot/controller/ChatBotRestController.java
  src/main/java/com/kcc/trioffice/domain/chat_bot/domain/ChatBot.java
  src/main/java/com/kcc/trioffice/domain/chat_bot/mapper/ChatBotMapper.java
  src/main/java/com/kcc/trioffice/domain/chat_bot/service/ChatBotService.java
  src/main/java/com/kcc/trioffice/global/chat_bot/ChatBotConfig.java
  src/main/java/com/kcc/trioffice/global/chat_bot/CustomChatBotOptions.java
  src/main/resources/mapper/chat-bot.xml
  src/main/webapp/WEB-INF/views/component/first-side-bar.jsp
  src/main/webapp/static/component/first-side-bar.css
  src/main/webapp/static/component/first-side-bar.js
  src/main/webapp/static/component/top-bar.css
  src/main/webapp/static/schedule/schedule.js
Labels: feat

#71 hotfix: 기본 경로 로그인 페이지로 리다이렉트
  src/main/java/com/kcc/trioffice/domain/employee/controller/EmployeeController.java
Labels: fix

#73 hotfix: 아이디 저장하기, url
  src/main/java/com/kcc/trioffice/domain/schedule/service/ScheduleService.java
  src/main/webapp/WEB-INF/views/user/login.jsp
  src/main/webapp/static/user/login.css
Labels: fix

#78 refactor: 코드 개선
  src/main/java/com/kcc/trioffice/domain/attached_file/controller/AttachedFileRestController.java
  src/main/java/com/kcc/trioffice/domain/attached_file/mapper/AttachedFileMapper.java
  src/main/java/com/kcc/trioffice/domain/attached_file/service/AttachedFileService.java
  src/main/java/com/kcc/trioffice/domain/chat_bot/controller/ChatBotRestController.java
  src/main/java/com/kcc/trioffice/domain/chat_bot/service/ChatBotService.java
  src/main/java/com/kcc/trioffice/domain/chat_room/controller/ChatRoomController.java
  src/main/java/com/kcc/trioffice/domain/chat_room/controller/ChatRoomRestController.java
  src/main/java/com/kcc/trioffice/domain/chat_room/controller/ChatRoomSocketController.java
  src/main/java/com/kcc/trioffice/domain/chat_room/dto/response/ChatRoomDetailInfo.java
  src/main/java/com/kcc/trioffice/domain/chat_room/dto/response/ChatRoomInfo.java
  src/main/java/com/kcc/trioffice/domain/chat_room/dto/response/ChatRoomInfoBase.java
  src/main/java/com/kcc/trioffice/domain/chat_room/mapper/ChatMapper.java
  src/main/java/com/kcc/trioffice/domain/chat_room/mapper/ChatRoomMapper.java
  src/main/java/com/kcc/trioffice/domain/chat_room/service/ChatRoomService.java
  src/main/java/com/kcc/trioffice/domain/chat_status/controller/ChatStatusRestController.java
  src/main/java/com/kcc/trioffice/domain/chat_status/dto/response/EmoticonMessage.java
  src/main/java/com/kcc/trioffice/domain/chat_status/mapper/ChatStatusMapper.java
  src/main/java/com/kcc/trioffice/domain/chat_status/service/ChatStatusService.java
  src/main/java/com/kcc/trioffice/domain/employee/controller/EmployeeRestController.java
  src/main/java/com/kcc/trioffice/domain/employee/mapper/EmployeeMapper.java
  src/main/java/com/kcc/trioffice/domain/employee/service/EmployeeService.java
  src/main/java/com/kcc/trioffice/domain/notification/mapper/NotificationMapper.java
  src/main/java/com/kcc/trioffice/domain/participation_employee/controller/ParticipationEmployeeRestController.java
  src/main/java/com/kcc/trioffice/domain/participation_employee/mapper/ParticipationEmployeeMapper.java
  src/main/java/com/kcc/trioffice/domain/participation_employee/service/ParticipationEmployeeService.java
  src/main/java/com/kcc/trioffice/global/auth/PrincipalDetailService.java
  src/main/java/com/kcc/trioffice/global/constant/GlobalConstants.java
  src/main/java/com/kcc/trioffice/global/event/PtptEvent.java
  src/main/java/com/kcc/trioffice/global/exception/GlobalExceptionHandler.java
  src/main/java/com/kcc/trioffice/global/handler/StompHandler.java
  src/main/resources/mapper/participation-employee.xml
  src/main/webapp/static/chat_room/chat-room.js
Labels: fix, refactor

#79 refactor: employeeStatus, 무한스크롤
  src/main/java/com/kcc/trioffice/global/config/SecurityConfig.java
  src/main/java/com/kcc/trioffice/global/handler/CustomLoginSuccessHandler.java
  src/main/java/com/kcc/trioffice/global/handler/CustomLogoutSuccessHandler.java
  src/main/resources/mapper/chat-room.xml
  src/main/webapp/WEB-INF/views/chat_room/chat-room-list.jsp
  src/main/webapp/static/chat_room/chat-room-list.css
  src/main/webapp/static/chat_room/chat-room.js
  src/main/webapp/static/component/top-bar.js
  src/main/webapp/static/notification/notification.css
Labels: fix, refactor

#80 refactor: 알림 개선
  src/main/java/com/kcc/trioffice/TriofficeApplication.java
  src/main/java/com/kcc/trioffice/domain/chat_room/service/ChatRoomService.java
  src/main/java/com/kcc/trioffice/domain/notification/dto/request/SendPushDto.java
  src/main/java/com/kcc/trioffice/domain/notification/service/FcmService.java
  src/main/java/com/kcc/trioffice/global/config/RedisConfig.java
  src/main/java/com/kcc/trioffice/global/constant/GlobalConstants.java
  src/main/java/com/kcc/trioffice/global/redis/RedisService.java
  src/main/webapp/WEB-INF/views/chat_room/chat-room-list.jsp
  src/main/webapp/WEB-INF/views/component/firebase-config.jsp
  src/main/webapp/WEB-INF/views/component/lib.jsp
  src/main/webapp/static/chat_room/chat-room-list.css
  src/main/webapp/static/chat_room/chat-room.js
Labels: fix, refactor

#81 feat: 챗봇
  pom.xml
  src/main/java/com/kcc/trioffice/domain/chat_bot/controller/ChatBotRestController.java
  src/main/java/com/kcc/trioffice/domain/chat_bot/domain/Document.java
  src/main/java/com/kcc/trioffice/domain/chat_bot/mapper/ChatBotMapper.java
  src/main/java/com/kcc/trioffice/domain/chat_bot/service/ChatBotService.java
  src/main/java/com/kcc/trioffice/domain/chat_bot/service/VectorStoreService.java
  src/main/java/com/kcc/trioffice/domain/chat_room/dto/request/ChatRoomCreate.java
  src/main/java/com/kcc/trioffice/global/auth/PrincipalDetail.java
  src/main/java/com/kcc/trioffice/global/chat_bot/ChatBotConfig.java
  src/main/java/com/kcc/trioffice/global/chat_bot/CustomChatBotOptions.java
  src/main/java/com/kcc/trioffice/global/chat_bot/RedisConfig.java
  src/main/resources/mapper/chat-bot.xml
  src/main/webapp/WEB-INF/views/component/first-side-bar.jsp
  src/main/webapp/static/component/first-side-bar.js
  src/main/webapp/static/schedule/schedule.js
Labels: feat

#85 refactor: 알림 css 수정
  src/main/java/com/kcc/trioffice/domain/chat_room/service/ChatRoomService.java
  src/main/java/com/kcc/trioffice/global/handler/CustomLoginSuccessHandler.java
  src/main/resources/mapper/schedule.xml
  src/main/webapp/WEB-INF/views/notification/notification.jsp
  src/main/webapp/static/chat_room/chat-room.js
  src/main/webapp/static/chat_room/modal/send-file-modal.js
  src/main/webapp/static/notification/notification.css
  src/main/webapp/static/notification/notification.js
Labels: feat, refactor

#86 refactor: 주석 및 들여쓰기
  src/main/java/com/kcc/trioffice/domain/attached_file/controller/AttachedFileRestController.java
  src/main/java/com/kcc/trioffice/domain/attached_file/service/AttachedFileService.java
  src/main/java/com/kcc/trioffice/domain/chat_room/controller/ChatRoomController.java
  src/main/java/com/kcc/trioffice/domain/chat_room/controller/ChatRoomRestController.java
  src/main/java/com/kcc/trioffice/domain/chat_room/controller/ChatRoomSocketController.java
  src/main/java/com/kcc/trioffice/domain/chat_status/controller/ChatStatusRestController.java
  src/main/java/com/kcc/trioffice/domain/chat_status/service/ChatStatusService.java
  src/main/java/com/kcc/trioffice/domain/notification/controller/NotificationController.java
  src/main/java/com/kcc/trioffice/domain/notification/controller/NotificationRestController.java
  src/main/java/com/kcc/trioffice/domain/notification/service/FcmService.java
  src/main/java/com/kcc/trioffice/domain/notification/service/NotificationService.java
  src/main/java/com/kcc/trioffice/domain/participation_employee/controller/ParticipationEmployeeRestController.java
  src/main/java/com/kcc/trioffice/domain/participation_employee/service/ParticipationEmployeeService.java
  src/main/resources/mapper/attached-file.xml
  src/main/resources/mapper/chat-bot.xml
  src/main/resources/mapper/chat-room.xml
  src/main/resources/mapper/chat-status.xml
  src/main/resources/mapper/department.xml
  src/main/resources/mapper/employee.xml
  src/main/webapp/static/chat_room/modal/send-file-modal.css
  src/main/webapp/static/notification/notification.css
  src/main/webapp/static/notification/notification.js
Labels: refactor

#87 feat: 관리자 조직도 부서 CRUD
  src/main/java/com/kcc/trioffice/domain/company/dto/response/Company.java
  src/main/java/com/kcc/trioffice/domain/department/controller/DepartmentController.java
  src/main/java/com/kcc/trioffice/domain/department/controller/DepartmentRestController.java
  src/main/java/com/kcc/trioffice/domain/department/dto/response/Department.java
  src/main/java/com/kcc/trioffice/domain/department/mapper/DepartmentMapper.java
  src/main/java/com/kcc/trioffice/domain/department/service/DepartmentService.java
  src/main/resources/mapper/department.xml
  src/main/webapp/WEB-INF/views/department/adminDepartment.jsp
  src/main/webapp/static/department/adminDepartment.css
Labels: feat

#89 feat: 검색창
  src/main/java/com/kcc/trioffice/domain/chat_bot/domain/ChatBot.java
  src/main/java/com/kcc/trioffice/domain/common/controller/ChatBotRestController.java
  src/main/java/com/kcc/trioffice/domain/common/controller/SearchRestController.java
  src/main/java/com/kcc/trioffice/domain/common/domain/ChatBot.java
  src/main/java/com/kcc/trioffice/domain/common/domain/Document.java
  src/main/java/com/kcc/trioffice/domain/common/domain/ResponseSearch.java
  src/main/java/com/kcc/trioffice/domain/common/domain/SearchChatRoom.java
  src/main/java/com/kcc/trioffice/domain/common/mapper/ChatBotMapper.java
  src/main/java/com/kcc/trioffice/domain/common/mapper/SearchMapper.java
  src/main/java/com/kcc/trioffice/domain/common/service/ChatBotService.java
  src/main/java/com/kcc/trioffice/domain/common/service/SearchService.java
  src/main/java/com/kcc/trioffice/domain/common/service/VectorStoreService.java
  src/main/java/com/kcc/trioffice/domain/employee/dto/response/SearchEmployee.java
  src/main/resources/mapper/chat-bot.xml
  src/main/resources/mapper/search.xml
  src/main/webapp/WEB-INF/views/component/top-bar.jsp
  src/main/webapp/static/component/top-bar.css
  src/main/webapp/static/component/top-bar.js
Labels: feat

#90 refactor: 전체적인 css 변경
  src/main/java/com/kcc/trioffice/domain/chat_room/service/ChatRoomService.java
  src/main/webapp/WEB-INF/views/notification/notification.jsp
  src/main/webapp/static/chat_room/chat-room.js
  src/main/webapp/static/chat_room/modal/chat-room-dropdown.css
  src/main/webapp/static/component/common.js
  src/main/webapp/static/notification/notification.css
Labels: refactor

#91 hotfix: 파일 다운로드 오류 수정
  src/main/webapp/static/chat_room/chat-room.js
Labels: fix

#93 refector: 피드백 후 디자인 수정 #92
  src/main/webapp/WEB-INF/views/schedule/schedule.jsp
  src/main/webapp/WEB-INF/views/user/find-password-email.jsp
  src/main/webapp/WEB-INF/views/user/find-password.jsp
  src/main/webapp/WEB-INF/views/user/login.jsp
  src/main/webapp/static/schedule/schedule.css
  src/main/webapp/static/schedule/schedule.js
  src/main/webapp/static/user/find-password.js
  src/main/webapp/static/user/login.css
Labels: refactor

#94 hotfix: side bar alien-item 옵션 삭제 및 css 재조정
  src/main/java/com/kcc/trioffice/domain/common/controller/OtherEmployeeRestController.java
  src/main/java/com/kcc/trioffice/domain/common/domain/EmployeeInfoWithDept.java
  src/main/java/com/kcc/trioffice/domain/common/mapper/OtherEmployeeMapper.java
  src/main/java/com/kcc/trioffice/domain/common/service/OtherEmployeeService.java
  src/main/resources/mapper/other.xml
  src/main/webapp/WEB-INF/views/component/top-bar.jsp
  src/main/webapp/static/component/top-bar.css
  src/main/webapp/static/component/top-bar.js
Labels: fix

#95 hotfix: side bar css 원복
  src/main/webapp/WEB-INF/views/component/first-side-bar.jsp
  src/main/webapp/static/component/first-side-bar.css
  src/main/webapp/static/component/top-bar.css
Labels: fix, refactor

#96 refactor: notification css 수정
  src/main/webapp/WEB-INF/views/notification/notification.jsp
  src/main/webapp/static/chat_room/chat-room.js
  src/main/webapp/static/notification/notification.css
Labels: fix, refactor

#99 feat: 다른 사용자 정보 조회
  src/main/java/com/kcc/trioffice/domain/chat_room/controller/ChatRoomController.java
  src/main/java/com/kcc/trioffice/domain/chat_room/dto/response/ChatInfoAndRedirectNum.java
  src/main/java/com/kcc/trioffice/domain/chat_room/service/ChatRoomService.java
  src/main/java/com/kcc/trioffice/domain/common/domain/SearchChatRoom.java
  src/main/java/com/kcc/trioffice/domain/common/service/SearchService.java
  src/main/java/com/kcc/trioffice/domain/schedule/controller/ScheduleRestController.java
  src/main/java/com/kcc/trioffice/domain/schedule/mapper/ScheduleMapper.java
  src/main/java/com/kcc/trioffice/domain/schedule/service/ScheduleService.java
  src/main/resources/mapper/schedule.xml
  src/main/resources/mapper/search.xml
  src/main/webapp/WEB-INF/views/component/top-bar.jsp
  src/main/webapp/WEB-INF/views/department/department.jsp
  src/main/webapp/WEB-INF/views/schedule/schedule.jsp
  src/main/webapp/WEB-INF/views/user/find-password-email.jsp
  src/main/webapp/WEB-INF/views/user/find-password.jsp
  src/main/webapp/static/component/top-bar.css
  src/main/webapp/static/component/top-bar.js
  src/main/webapp/static/department/department.css
  src/main/webapp/static/schedule/schedule.css
  src/main/webapp/static/schedule/schedule.js
Labels: feat
