Repository KccTrio/final_project, pull requests merged in 2024-11, with the labels that each got.

#101 feat: 파일 통합 관리
  src/main/java/com/kcc/trioffice/domain/attached_file/controller/AttachedFileController.java
  src/main/java/com/kcc/trioffice/domain/attached_file/controller/AttachedFileRestController.java
  src/main/java/com/kcc/trioffice/domain/attached_file/dto/request/AttachedFileSelect.java
  src/main/java/com/kcc/trioffice/domain/attached_file/dto/response/AttachedFileDetailInfo.java
  src/main/java/com/kcc/trioffice/domain/attached_file/mapper/AttachedFileMapper.java
  src/main/java/com/kcc/trioffice/domain/attached_file/service/AttachedFileService.java
  src/main/java/com/kcc/trioffice/domain/common/controller/SearchRestController.java
  src/main/java/com/kcc/trioffice/domain/common/mapper/SearchMapper.java
  src/main/java/com/kcc/trioffice/domain/common/service/SearchService.java
  src/main/resources/mapper/attached-file.xml
  src/main/resources/mapper/search.xml
  src/main/webapp/WEB-INF/views/attached-file/attached-file.jsp
  src/main/webapp/WEB-INF/views/chat_room/chat-room-list.jsp
  src/main/webapp/WEB-INF/views/component/first-side-bar.jsp
  src/main/webapp/WEB-INF/views/component/lib.jsp
  src/main/webapp/WEB-INF/views/notification/notification.jsp
  src/main/webapp/static/attached-file/attached-file.css
  src/main/webapp/static/attached-file/attached-file.js
  src/main/webapp/static/chat_room/chat-room-list.css
  src/main/webapp/static/component/first-side-bar.css
Labels: feat

#103 hotfix: 탑바 수정 및 폰트 수정
  src/main/webapp/WEB-INF/views/chat_room/chat-room-list.jsp
  src/main/webapp/WEB-INF/views/chat_room/chat-room-save.jsp
  src/main/webapp/WEB-INF/views/chat_room/modal/image-detail-modal.jsp
  src/main/webapp/WEB-INF/views/component/lib.jsp
  src/main/webapp/static/chat_room/chat-room-save.css
  src/main/webapp/static/chat_room/modal/add-emp-modal.css
  src/main/webapp/static/component/top-bar.css
Labels: fix

#104 hotfix: top-bar size up 후 일정, 모달 사이즈 재조정
  src/main/webapp/WEB-INF/views/component/top-bar.jsp
  src/main/webapp/WEB-INF/views/schedule/schedule.jsp
  src/main/webapp/static/component/first-side-bar.css
  src/main/webapp/static/component/second-side-bar.css
  src/main/webapp/static/component/top-bar.css
  src/main/webapp/static/component/top-bar.js
  src/main/webapp/static/schedule/schedule-top-bar.css
Labels: refactor

#106 feat: 파일 미리보기
  src/main/java/com/kcc/trioffice/domain/attached_file/controller/AttachedFileRestController.java
  src/main/java/com/kcc/trioffice/domain/attached_file/service/AttachedFileService.java
  src/main/java/com/kcc/trioffice/global/image/service/S3FileService.java
  src/main/webapp/WEB-INF/views/chat_room/chat-room-list.jsp
  src/main/webapp/static/attached-file/attached-file.css
  src/main/webapp/static/attached-file/attached-file.js
  src/main/webapp/static/chat_room/chat-room-list.css
  src/main/webapp/static/chat_room/chat-room-save.css
  src/main/webapp/static/chat_room/chat-room.css
  src/main/webapp/static/chat_room/chat-room.js
  src/main/webapp/static/chat_room/modal/add-emp-modal.css
  src/main/webapp/static/chat_room/modal/participant-emp-modal.css
  src/main/webapp/static/chat_room/modal/send-file-modal.css
Labels: feat, refactor

#107 feat: 회원 상세조회
  src/main/java/com/kcc/trioffice/domain/employee/controller/EmployeeRestController.java
  src/main/java/com/kcc/trioffice/domain/employee/mapper/EmployeeMapper.java
  src/main/java/com/kcc/trioffice/domain/employee/service/EmployeeService.java
  src/main/resources/mapper/employee.xml
  src/main/webapp/static/component/top-bar.css
  src/main/webapp/static/component/top-bar.js
Labels: feat

#109 refactor: attached-file, chat-room, department 전체적인 css 구조 변경
  src/main/webapp/WEB-INF/views/attached-file/attached-file.jsp
  src/main/webapp/WEB-INF/views/chat_room/chat-room-list.jsp
  src/main/webapp/WEB-INF/views/department/department.jsp
  src/main/webapp/WEB-INF/views/notification/notification.jsp
  src/main/webapp/static/attached-file/attached-file.css
  src/main/webapp/static/chat_room/chat-room-list.css
  src/main/webapp/static/chat_room/chat-room-save.css
  src/main/webapp/static/chat_room/chat-room-save.js
  src/main/webapp/static/chat_room/chat-room.css
  src/main/webapp/static/component/second-side-bar.css
  src/main/webapp/static/department/department.css
  src/main/webapp/static/notification/notification.css
Labels: refactor

#111 refactor: 테이블 css 및 tagify css 변경
  src/main/webapp/WEB-INF/views/chat_room/chat-room-list.jsp
  src/main/webapp/static/attached-file/attached-file.css
  src/main/webapp/static/chat_room/chat-room-list.css
  src/main/webapp/static/chat_room/modal/send-file-modal.css
Labels: refactor

#112 feat: 회원 정보 수정 및 비밀번호 변경
  src/main/java/com/kcc/trioffice/domain/employee/RequestPassword.java
  src/main/java/com/kcc/trioffice/domain/employee/controller/EmployeeController.java
  src/main/java/com/kcc/trioffice/domain/employee/controller/EmployeeRestController.java
  src/main/java/com/kcc/trioffice/domain/employee/mapper/EmployeeMapper.java
  src/main/java/com/kcc/trioffice/domain/employee/service/EmployeeService.java
  src/main/resources/mapper/employee.xml
  src/main/webapp/WEB-INF/views/user/change-password.jsp
  src/main/webapp/WEB-INF/views/user/detail.jsp
  src/main/webapp/static/component/top-bar.js
  src/main/webapp/static/user/change-password.css
  src/main/webapp/static/user/change-password.js
  src/main/webapp/static/user/detail.css
  src/main/webapp/static/user/detail.js
Labels: feat

#113 refactor: 전체적인 css 수정
  src/main/resources/mapper/department.xml
  src/main/webapp/WEB-INF/views/chat_room/chat-room-list.jsp
  src/main/webapp/WEB-INF/views/schedule/schedule.jsp
  src/main/webapp/static/attached-file/attached-file.css
  src/main/webapp/static/chat_room/chat-room-list.css
  src/main/webapp/static/component/main-contents.css
  src/main/webapp/static/component/top-bar.css
  src/main/webapp/static/schedule/schedule.css
Labels: refactor

#114 refactor: 테이블 관련 css 통일
  src/main/java/com/kcc/trioffice/domain/attached_file/dto/response/AttachedFileInfo.java
  src/main/resources/mapper/attached-file.xml
  src/main/webapp/WEB-INF/views/chat_room/chat-room-list.jsp
  src/main/webapp/static/attached-file/attached-file.css
  src/main/webapp/static/attached-file/attached-file.js
  src/main/webapp/static/chat_room/chat-room-list.css
  src/main/webapp/static/chat_room/chat-room.js
Labels: refactor

#116 refector: 로그인쪽 css변경
  src/main/java/com/kcc/trioffice/domain/schedule/service/ScheduleService.java
  src/main/webapp/WEB-INF/views/component/top-bar.jsp
  src/main/webapp/WEB-INF/views/schedule/schedule.jsp
  src/main/webapp/WEB-INF/views/user/change-password.jsp
  src/main/webapp/static/attached-file/attached-file.css
  src/main/webapp/static/chat_room/chat-room-list.css
  src/main/webapp/static/component/main-contents.css
  src/main/webapp/static/component/second-side-bar.css
  src/main/webapp/static/component/top-bar.css
  src/main/webapp/static/schedule/schedule-top-bar.css
  src/main/webapp/static/schedule/schedule.css
  src/main/webapp/static/schedule/schedule.js
  src/main/webapp/static/user/change-password.css
  src/main/webapp/static/user/detail.css
  src/main/webapp/static/user/find-password.css
  src/main/webapp/static/user/login.css
Labels: refactor

#120 feat: mail acync 처리
  src/main/java/com/kcc/trioffice/domain/schedule/service/ScheduleService.java
Labels: refactor

#121 hotfix: width 변경
  src/main/webapp/static/chat_room/chat-room-save.css
Labels: fix

#122 hotfix: width 변경
  src/main/webapp/static/chat_room/chat-room-list.css
Labels: fix

#123 fix: file-name 크기 지정
  src/main/webapp/static/chat_room/chat-room.css
Labels: fix

#124 hotfix: 파일 전송시 profileUrl 안보이는 문제 해결
  src/main/java/com/kcc/trioffice/domain/attached_file/service/AttachedFileService.java
Labels: fix

#125 hotfix: 파일 이모티콘 클릭시 오류 해결 & 채팅 생성 취소시 디폴트 이미지로 변경
  src/main/webapp/static/chat_room/chat-room.js
Labels: fix

#126 fix: 토큰 받는 과정 및 오류 개선
  src/main/java/com/kcc/trioffice/domain/chat_room/service/ChatRoomService.java
  src/main/java/com/kcc/trioffice/domain/common/controller/TokenController.java
  src/main/java/com/kcc/trioffice/domain/notification/service/FcmService.java
  src/main/java/com/kcc/trioffice/global/config/AsyncConfig.java
  src/main/java/com/kcc/trioffice/global/handler/CustomLoginSuccessHandler.java
  src/main/resources/mapper/participation-employee.xml
  src/main/webapp/WEB-INF/views/chat_room/chat-room-list.jsp
  src/main/webapp/WEB-INF/views/component/loading.jsp
  src/main/webapp/WEB-INF/views/component/token-save.jsp
  src/main/webapp/WEB-INF/views/test-noti.jsp
Labels: fix

#127 feat: 로딩 스피너 적용
  src/main/webapp/WEB-INF/views/component/lib.jsp
  src/main/webapp/WEB-INF/views/component/token-save.jsp
  src/main/webapp/static/component/common.js
  src/main/webapp/static/component/main-contents.css
Labels: feat

#128 fix: 파일 다운로드 명 오류 해결, 채팅방 입장 메세지 위치 수정
  src/main/webapp/static/chat_room/chat-room.js
Labels: fix

#129 refactor: 메일 서비스 개선
  src/main/java/com/kcc/trioffice/domain/common/service/EmailService.java
  src/main/java/com/kcc/trioffice/domain/common/service/VectorStoreService.java
  src/main/java/com/kcc/trioffice/domain/schedule/service/ScheduleService.java
  src/main/webapp/WEB-INF/views/schedule/schedule.jsp
  src/main/webapp/static/schedule/schedule-top-bar.css
  src/main/webapp/static/schedule/schedule.js
Labels: refactor

#131 refactor: admin alert 통일
  src/main/webapp/WEB-INF/views/department/adminDepartment.jsp
  src/main/webapp/static/department/adminDepartment.css
Labels: refactor

#132 fix: cancel 버튼 수정
  src/main/webapp/WEB-INF/views/department/adminDepartment.jsp
  src/main/webapp/static/chat_room/chat-room.js
Labels: fix

#133 refactor: css 개선, 검색 fix, 로딩 스피너 fix, 프로필 이미지 null 처리
  src/main/java/com/kcc/trioffice/domain/common/mapper/SearchMapper.java
  src/main/java/com/kcc/trioffice/domain/common/service/OtherEmployeeService.java
  src/main/java/com/kcc/trioffice/domain/common/service/SearchService.java
  src/main/java/com/kcc/trioffice/domain/employee/service/EmployeeService.java
  src/main/java/com/kcc/trioffice/domain/schedule/service/ScheduleService.java
  src/main/java/com/kcc/trioffice/global/constant/GlobalConstants.java
  src/main/resources/mapper/search.xml
  src/main/webapp/WEB-INF/views/schedule/schedule.jsp
  src/main/webapp/WEB-INF/views/user/detail.jsp
  src/main/webapp/static/component/common.js
  src/main/webapp/static/component/top-bar.css
  src/main/webapp/static/component/top-bar.js
  src/main/webapp/static/schedule/schedule.js
Labels: fix, refactor

#134 refactor: 챗봇 가이드 조정
  src/main/java/com/kcc/trioffice/domain/common/service/SearchService.java
  src/main/java/com/kcc/trioffice/domain/common/service/VectorStoreService.java
  src/main/webapp/WEB-INF/views/component/first-side-bar.jsp
  src/main/webapp/static/component/common.js
  src/main/webapp/static/component/first-side-bar.css
  src/main/webapp/static/component/top-bar.css
Labels: refactor

#136 hotfix: 시작일 종료일 설정
  src/main/webapp/static/schedule/schedule.js
Labels: fix, refactor

#137 hotfix: 삭제된 사원 조회 X
  src/main/resources/mapper/search.xml
Labels: fix

#139 hotfix: width, height 조절
  src/main/webapp/static/attached-file/attached-file.css
Labels: fix
